language: node_js

node_js:
    - '10'

cache:
    npm: false

before_install:
    - npm i -g npm@6

script:
    - npm run lint
    - npm run test:unit
    - npm run test:func

deploy:
    provider: script
    skip_cleanup: true
    script:
        - npx semantic-release
    on:
        branch: release
